apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: {{ .values.mongodb.appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .values.mongodb.appName}}
  template:
    metadata:
      labels:
        app: {{ .values.mongodb.appName}}
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef: 
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: {{ .values.mongodb-deployment.appName}}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017