apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: alvin-cluster
  region: ap-southeast-1

vpc:
  id: "vpc-0a646b9a61ad41ae9"
  subnets:
    private:
      ap-southeast-1a:
        id: "subnet-0e42b36156cf200f0"
      ap-southeast-1b:
        id: "subnet-09068bafbe851e5a9"

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2